# Auto-generated by text-cli;install/uninstall. Do not edit manually.
# Format: (module_path, init_fn, arg_key, post_init_functions)
# arg_key: "db"=SQLITE_DB_FILE, "quota"=quota.db, "db_dict"=SQLITE_DB_PATH,
#           "project_root"=str(project_root), None=no args

HANDLER_INITS = []

# Dispatch callbacks to inject after init (module, setter_fn)
DISPATCH_INJECTS = [
    ("handlers.key", "_set_dispatch"),
    ("handlers.task_manager", "_set_task_dispatch"),
]
