# Auto-generated by text-cli;install/uninstall. Do not edit manually.
# Format: (module_path, init_fn, arg_key, post_init_functions)
# arg_key: "db"=SQLITE_DB_FILE, "quota"=quota.db, "db_dict"=SQLITE_DB_PATH,
#           "project_root"=str(project_root), None=no args
#
# A3 base platform: empty — SQLite-backed handlers (key, task_manager, etc.)
# are registered in A6/A9 layers via their own handler_inits.py copies.

HANDLER_INITS = [
]

# Dispatch callbacks to inject after init (module, setter_fn)
DISPATCH_INJECTS = [
]
