#!/usr/bin/env python3
"""
build-all.py — Build complete deploy artifacts from src/skeleton/.

Semantics:
  src/skeleton/{group}/{layer}/ = skeleton source of truth (developers edit only here)
  deploy/{layer}/ = complete deployable artifact (generated by this script)

Rules:
  - Source files → overwrite deploy/ same-name paths (later layers override
    earlier, A2→A9 cumulative accretion).
  - Deploy-only files → never deleted by the build; reported as stale warnings
    by --check (does NOT block CI).
  - Source-deleted files → --check warns (does NOT block CI).

A0/A1/A5/BYPASS through mode: direct sync from src/skeleton/ → deploy/, no accretion.

Package distribution: copy src/text_cli/open_text_cli/standard-python/ → deploy/packages/ (flatten).

Usage:
  python scripts/build-all.py              # sync all layers
  python scripts/build-all.py A3           # sync single layer
  python scripts/build-all.py packages     # distribute packages only
  python scripts/build-all.py --check      # CI check: errors block, stale warns
  python scripts/build-all.py --check A4   # check single layer
"""

import argparse
import filecmp
import os
import pathlib
import shutil
import sys

THIS_FILE = pathlib.Path(__file__).resolve()
PROJECT_ROOT = THIS_FILE.parent.parent
SKELETON_ROOT = PROJECT_ROOT / "src" / "skeleton"
DEPLOY_ROOT = PROJECT_ROOT / "deploy"
PACKAGES_SOURCE = PROJECT_ROOT / "src" / "text_cli" / "open_text_cli" / "standard-python"
PACKAGES_DEPLOY = PROJECT_ROOT / "deploy" / "packages"

# Skeleton accretion chain: group/layer format, A2→A9 cumulative overlay.
LAYER_CHAIN = [
    ("A2", "copilot/A2-copilot"),
    ("A3", "service/A3-service"),
    ("A4", "service/A4-paths"),
    ("A6", "service/A6-sql"),
    ("A7", "service/A7-mcp"),
    ("A8", "service/A8-discovery"),
    ("A9", "service/A9-advanced"),
]

# A0/A5/BYPASS through layers: direct sync src/skeleton/ → deploy/, no accretion.
THROUGH_LAYERS = [
    ("A0", "base/A0-protocol"),
    ("A5", "endpoint/A5-endpoint"),
    ("BYPASS", "bypass-service"),
]

# A1 dependent layer: copies A0 SDK first, then A1 itself on top.
# deploy/A1-skill/ = A0 SDK + A1 infrastructure (self-contained).
DEPENDENT_LAYERS = [
    ("A1", "base/A1-skill", ["base/A0-protocol"]),
]

# Whitelist of subdirectories within skeleton layers to include in the build.
SKELETON_SUBDIRS = {"service", "copilot", "media", "MCPservice", "aggregate",
                    "other", "handlers", "packages", "config"}

# Directories excluded from os.walk traversal (runtime artifacts).
_EXCLUDED_DIRS = frozenset({"__pycache__"})

# Files excluded from propagation (dev-only, not part of deployed runtime).
_EXCLUDED_FILES = frozenset({".gitkeep", ".gitignore", "pytest.ini"})


def collect_source(layer_path: str) -> dict[str, pathlib.Path]:
    """Collect all source files from src/skeleton/{group}/{layer}/."""
    source_dir = SKELETON_ROOT / layer_path
    if not source_dir.is_dir():
        return {}
    files = {}
    for root, dirs, filenames in os.walk(str(source_dir)):
        dirs[:] = [d for d in dirs if d not in _EXCLUDED_DIRS]
        root_path = pathlib.Path(root)
        rel_dir = root_path.relative_to(source_dir)
        if rel_dir != pathlib.Path("."):
            top = str(rel_dir).split(os.sep)[0]
            if top not in SKELETON_SUBDIRS:
                continue
        for fname in filenames:
            if fname in _EXCLUDED_FILES:
                continue
            rel = str(rel_dir / fname) if rel_dir != pathlib.Path(".") else fname
            files[rel] = root_path / fname
    return files


def resolve_source_files(layer_id: str, layer_path: str,
                         chain: list[tuple[str, str]]) -> dict[str, pathlib.Path]:
    """Accumulate source files layer by layer; later layers override earlier."""
    accumulated: dict[str, pathlib.Path] = {}
    for lid, lpath in chain:
        layer_files = collect_source(lpath)
        accumulated.update(layer_files)
        if lid == layer_id:
            break
    return accumulated


def build_layer(layer_id: str, layer_path: str,
                chain: list[tuple[str, str]]) -> dict:
    """Build a single layer: source → deploy/{layer}/."""
    layer_name = layer_path.split("/")[-1]
    deploy_dir = DEPLOY_ROOT / layer_name
    deploy_dir.mkdir(parents=True, exist_ok=True)
    expected = resolve_source_files(layer_id, layer_path, chain)

    current_files: dict[str, pathlib.Path] = {}
    for root, dirs, filenames in os.walk(str(deploy_dir)):
        dirs[:] = [d for d in dirs if d not in _EXCLUDED_DIRS]
        root_path = pathlib.Path(root)
        rel_dir = root_path.relative_to(deploy_dir)
        if rel_dir != pathlib.Path("."):
            top = str(rel_dir).split(os.sep)[0]
            if top not in SKELETON_SUBDIRS:
                continue
        for fname in filenames:
            rel = str(rel_dir / fname)
            current_files[rel] = root_path / fname

    overlaid = []
    stale = []
    for rel, src in sorted(expected.items()):
        dst = deploy_dir / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        if dst.exists():
            if filecmp.cmp(str(src), str(dst), shallow=False):
                continue
        shutil.copy2(str(src), str(dst))
        overlaid.append(rel)

    for rel in sorted(current_files):
        if rel not in expected and not (rel == ".gitkeep" or rel.endswith("/.gitkeep")):
            stale.append(rel)

    return {"overlaid": overlaid, "stale": stale, "total_source": len(expected)}


def build_through_layer(layer_id: str, layer_path: str) -> dict:
    """Through build: src/skeleton/base/{layer}/ → deploy/{layer}/. No accretion."""
    source_dir = SKELETON_ROOT / layer_path
    layer_name = layer_path.split("/")[-1]
    deploy_dir = DEPLOY_ROOT / layer_name
    deploy_dir.mkdir(parents=True, exist_ok=True)

    if not source_dir.is_dir():
        return {"overlaid": [], "stale": [], "total_source": 0}

    expected = _collect_source_files(source_dir)

    overlaid = []
    for rel, src in sorted(expected.items()):
        dst = deploy_dir / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        if dst.exists():
            if filecmp.cmp(str(src), str(dst), shallow=False):
                continue
        shutil.copy2(str(src), str(dst))
        overlaid.append(rel)

    return {"overlaid": overlaid, "stale": [], "total_source": len(expected)}


def build_dependent_layer(layer_id: str, primary_path: str, dep_paths: list[str]) -> dict:
    """Dependent build: copy deps first, then primary layer on top.
    
    deploy/{layer_name}/ = copy(dep_0) + copy(dep_1) + ... + copy(primary).
    Primary overwrites deps on filename collision.
    """
    layer_name = primary_path.split("/")[-1]
    deploy_dir = DEPLOY_ROOT / layer_name
    deploy_dir.mkdir(parents=True, exist_ok=True)

    overlaid = []
    total_source = 0

    # Step 1: copy dependencies
    for dp in dep_paths:
        dep_dir = SKELETON_ROOT / dp
        if not dep_dir.is_dir():
            continue
        dep_expected = _collect_source_files(dep_dir)
        total_source += len(dep_expected)
        for rel, src in sorted(dep_expected.items()):
            dst = deploy_dir / rel
            dst.parent.mkdir(parents=True, exist_ok=True)
            if dst.exists():
                if filecmp.cmp(str(src), str(dst), shallow=False):
                    continue
            shutil.copy2(str(src), str(dst))
            overlaid.append(f"[{layer_id}:dep:{dp}] {rel}")

    # Step 2: copy primary layer (overwrites deps on collision)
    primary_dir = SKELETON_ROOT / primary_path
    if primary_dir.is_dir():
        primary_expected = _collect_source_files(primary_dir)
        total_source += len(primary_expected)
        for rel, src in sorted(primary_expected.items()):
            dst = deploy_dir / rel
            dst.parent.mkdir(parents=True, exist_ok=True)
            if dst.exists():
                if filecmp.cmp(str(src), str(dst), shallow=False):
                    continue
            shutil.copy2(str(src), str(dst))
            overlaid.append(f"[{layer_id}] {rel}")

    return {"overlaid": overlaid, "stale": [], "total_source": total_source}


def _collect_source_files(source_dir: pathlib.Path) -> dict[str, pathlib.Path]:
    """Walk source_dir and return {rel_path: abs_path} for all non-excluded files."""
    expected: dict[str, pathlib.Path] = {}
    for root, dirs, filenames in os.walk(str(source_dir)):
        dirs[:] = [d for d in dirs if d not in _EXCLUDED_DIRS]
        root_path = pathlib.Path(root)
        rel_dir = root_path.relative_to(source_dir)
        for fname in filenames:
            if fname in _EXCLUDED_FILES:
                continue
            rel = str(rel_dir / fname) if rel_dir != pathlib.Path(".") else fname
            expected[rel] = root_path / fname
    return expected


def build_packages() -> dict:
    """Copy src/text_cli/open_text_cli/standard-python/ → deploy/packages/ (flatten)."""
    PACKAGES_DEPLOY.mkdir(parents=True, exist_ok=True)
    if not PACKAGES_SOURCE.is_dir():
        return {"overlaid": [], "total_source": 0}

    expected: dict[str, pathlib.Path] = {}
    for root, dirs, filenames in os.walk(str(PACKAGES_SOURCE)):
        root_path = pathlib.Path(root)
        rel_dir = root_path.relative_to(PACKAGES_SOURCE)
        dirs[:] = [d for d in dirs if d not in _EXCLUDED_DIRS]
        for fname in filenames:
            rel = str(rel_dir / fname) if rel_dir != pathlib.Path(".") else fname
            expected[rel] = root_path / fname

    overlaid = []
    for rel, src in sorted(expected.items()):
        dst = PACKAGES_DEPLOY / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        if dst.exists():
            if filecmp.cmp(str(src), str(dst), shallow=False):
                continue
        shutil.copy2(str(src), str(dst))
        overlaid.append(rel)

    return {"overlaid": overlaid, "total_source": len(expected)}


def check_packages() -> tuple[bool, str, list[str]]:
    """Verify standard-python/ → deploy/packages/ consistency."""
    if not PACKAGES_DEPLOY.is_dir():
        return False, "deploy/packages missing", []
    if not PACKAGES_SOURCE.is_dir():
        return True, "no standard-python source (skip)", []

    expected: dict[str, pathlib.Path] = {}
    for root, dirs, filenames in os.walk(str(PACKAGES_SOURCE)):
        root_path = pathlib.Path(root)
        rel_dir = root_path.relative_to(PACKAGES_SOURCE)
        dirs[:] = [d for d in dirs if d not in _EXCLUDED_DIRS]
        for fname in filenames:
            rel = str(rel_dir / fname) if rel_dir != pathlib.Path(".") else fname
            expected[rel] = root_path / fname

    errors = []
    for rel, src in sorted(expected.items()):
        dst = PACKAGES_DEPLOY / rel
        if not dst.is_file():
            errors.append(f"  - missing: {rel}")
        elif not filecmp.cmp(str(src), str(dst), shallow=False):
            errors.append(f"  ~ diff:    {rel}")

    if errors:
        return False, f"packages: {len(errors)} error(s)", errors
    return True, f"packages: OK ({len(expected)} files)", []


def build_all():
    """Build all layers."""
    print("Skeleton layers (accretion):")
    for lid, lpath in LAYER_CHAIN:
        r = build_layer(lid, lpath, LAYER_CHAIN)
        parts = [f"{lid}: {r['total_source']} source files"]
        if r["overlaid"]:
            parts.append(f"{len(r['overlaid'])} overlaid")
        if r["stale"]:
            parts.append(f"[WARN] {len(r['stale'])} stale")
        status = "[OK]" if not r["stale"] else "[WARN]"
        print(f"  {status} {', '.join(parts)}")
        for f in r["overlaid"]:
            print(f"     + {f}")
        for f in r["stale"]:
            print(f"     ~ stale: {f}")

    print("Through layers (A0/A5/BYPASS):")
    for lid, lpath in THROUGH_LAYERS:
        r = build_through_layer(lid, lpath)
        parts = [f"{lid}: {r['total_source']} source files"]
        if r["overlaid"]:
            parts.append(f"{len(r['overlaid'])} overlaid")
        status = "[OK]"
        print(f"  {status} {', '.join(parts)}")
        for f in r["overlaid"]:
            print(f"     + {f}")

    print("Dependent layers (A1 = A0 + A1-skill):")
    for lid, lpath, deps in DEPENDENT_LAYERS:
        r = build_dependent_layer(lid, lpath, deps)
        parts = [f"{lid}: {r['total_source']} source files"]
        if r["overlaid"]:
            parts.append(f"{len(r['overlaid'])} overlaid")
        status = "[OK]"
        print(f"  {status} {', '.join(parts)}")
        for f in r["overlaid"]:
            print(f"     + {f}")

    print("Package distribution (standard-python/ → deploy/packages/):")
    r = build_packages()
    if r["total_source"] > 0:
        parts = [f"{r['total_source']} source files"]
        if r["overlaid"]:
            parts.append(f"{len(r['overlaid'])} overlaid")
        print(f"  [OK] {', '.join(parts)}")
        for f in r["overlaid"]:
            print(f"     + {f}")
    else:
        print("  [OK] standard-python/ is empty — no packages to distribute")


def check_layer(layer_id: str, layer_path: str,
                chain: list[tuple[str, str]]) -> tuple[bool, str, list[str], list[str]]:
    """Check one layer. Returns (ok, msg, errors, warnings)."""
    layer_name = layer_path.split("/")[-1]
    deploy_dir = DEPLOY_ROOT / layer_name
    if not deploy_dir.is_dir():
        return False, f"{layer_id}: deploy/{layer_name} missing", [], []

    expected = resolve_source_files(layer_id, layer_path, chain)
    errors = []
    warnings = []

    current_files: dict[str, pathlib.Path] = {}
    for root, dirs, filenames in os.walk(str(deploy_dir)):
        dirs[:] = [d for d in dirs if d not in _EXCLUDED_DIRS]
        root_path = pathlib.Path(root)
        rel_dir = root_path.relative_to(deploy_dir)
        if rel_dir != pathlib.Path("."):
            top = str(rel_dir).split(os.sep)[0]
            if top not in SKELETON_SUBDIRS:
                continue
        for fname in filenames:
            rel = str(rel_dir / fname) if rel_dir != pathlib.Path(".") else fname
            current_files[rel] = root_path / fname

    for rel, src in sorted(expected.items()):
        dst = deploy_dir / rel
        if not dst.is_file():
            errors.append(f"  - missing: {rel}")
        elif not filecmp.cmp(str(src), str(dst), shallow=False):
            errors.append(f"  ~ diff:    {rel}")

    for rel in sorted(current_files):
        if rel not in expected and not (rel == ".gitkeep" or rel.endswith("/.gitkeep")):
            warnings.append(f"  ! stale:   {rel}")

    has_errors = len(errors) > 0
    has_warnings = len(warnings) > 0

    if has_errors:
        msg = f"{layer_id}: {len(errors)} error(s)"
        if has_warnings:
            msg += f", {len(warnings)} warning(s)"
        return False, msg, errors, warnings
    if has_warnings:
        return True, f"{layer_id}: OK ({len(expected)} files, {len(warnings)} stale)", [], warnings
    return True, f"{layer_id}: OK ({len(expected)} files)", [], []


def check_through_layer(layer_id: str, layer_path: str) -> tuple[bool, str, list[str], list[str]]:
    """Check one through layer."""
    source_dir = SKELETON_ROOT / layer_path
    layer_name = layer_path.split("/")[-1]
    deploy_dir = DEPLOY_ROOT / layer_name

    if not deploy_dir.is_dir():
        return False, f"{layer_id}: deploy/{layer_name} missing", [], []
    if not source_dir.is_dir():
        return True, f"{layer_id}: no source (skip)", [], []

    expected: dict[str, pathlib.Path] = {}
    for root, dirs, filenames in os.walk(str(source_dir)):
        dirs[:] = [d for d in dirs if d not in _EXCLUDED_DIRS]
        root_path = pathlib.Path(root)
        rel_dir = root_path.relative_to(source_dir)
        for fname in filenames:
            if fname in _EXCLUDED_FILES:
                continue
            rel = str(rel_dir / fname) if rel_dir != pathlib.Path(".") else fname
            expected[rel] = root_path / fname

    errors = []
    for rel, src in sorted(expected.items()):
        dst = deploy_dir / rel
        if not dst.is_file():
            errors.append(f"  - missing: {rel}")
        elif not filecmp.cmp(str(src), str(dst), shallow=False):
            errors.append(f"  ~ diff:    {rel}")

    if errors:
        return False, f"{layer_id}: {len(errors)} error(s)", errors, []
    return True, f"{layer_id}: OK ({len(expected)} files)", [], []


def check_all() -> bool:
    """Check all layers."""
    all_ok = True
    print("Skeleton layers:")
    for lid, lpath in LAYER_CHAIN:
        ok, msg, errors, warnings = check_layer(lid, lpath, LAYER_CHAIN)
        if ok:
            icon = "[WARN]" if warnings else "[OK]"
            print(f"  {icon} {msg}")
            for w in warnings:
                print(w)
        else:
            print(f"  [ERR] {msg}")
            for e in errors:
                print(e)
            for w in warnings:
                print(w)
            all_ok = False

    print("Through layers:")
    for lid, lpath in THROUGH_LAYERS:
        ok, msg, errors, warnings = check_through_layer(lid, lpath)
        if ok:
            print(f"  [OK] {msg}")
        else:
            print(f"  [ERR] {msg}")
            for e in errors:
                print(e)
            all_ok = False

    print("Dependent layers:")
    for lid, lpath, deps in DEPENDENT_LAYERS:
        r = build_dependent_layer(lid, lpath, deps)
        layer_ok = len(r["overlaid"]) == 0
        if layer_ok:
            print(f"  [OK] {lid}: {r['total_source']} files unchanged")
        else:
            print(f"  [ERR] {lid}: {len(r['overlaid'])} files differ")
            for f in r["overlaid"]:
                print(f"     ~ {f}")
            all_ok = False

    print("Package distribution:")
    ok, msg, errors = check_packages()
    if ok:
        print(f"  [OK] {msg}")
    else:
        print(f"  [ERR] {msg}")
        for e in errors:
            print(e)
        all_ok = False

    return all_ok


def main():
    parser = argparse.ArgumentParser(
        description="Build complete deploy artifacts from src/skeleton/ layers"
    )
    parser.add_argument("target", nargs="?", default=None)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--project-root", default=str(PROJECT_ROOT))
    args = parser.parse_args()

    project_root = pathlib.Path(args.project_root).resolve()
    if not project_root.is_dir():
        print(f"Error: directory not found — {project_root}", file=sys.stderr)
        sys.exit(2)

    # Update global paths for the specified project root.
    global SKELETON_ROOT, DEPLOY_ROOT, PACKAGES_SOURCE, PACKAGES_DEPLOY
    SKELETON_ROOT = project_root / "src" / "skeleton"
    DEPLOY_ROOT = project_root / "deploy"
    PACKAGES_SOURCE = project_root / "src" / "text_cli" / "open_text_cli"
    PACKAGES_DEPLOY = project_root / "deploy" / "packages"

    target_path = None
    target_is_through = False
    target_is_dependent = False
    target_dep_paths = []
    target_is_packages = False
    if args.target:
        if args.target == "packages":
            target_is_packages = True
        else:
            for lid, lpath in LAYER_CHAIN:
                if lid == args.target:
                    target_path = lpath
                    break
            if not target_path:
                for lid, lpath in THROUGH_LAYERS:
                    if lid == args.target:
                        target_path = lpath
                        target_is_through = True
                        break
            if not target_path:
                for lid, lpath, deps in DEPENDENT_LAYERS:
                    if lid == args.target:
                        target_path = lpath
                        target_is_dependent = True
                        target_dep_paths = deps
                        break
        if not target_path and not target_is_packages:
            print(f"Error: unknown layer — {args.target}", file=sys.stderr)
            sys.exit(2)

    if args.check:
        if args.target:
            if target_is_packages:
                ok, msg, errors = check_packages()
                if ok:
                    print(f"[OK] {msg}")
                    sys.exit(0)
                else:
                    print(f"[ERR] {msg}")
                    for e in errors:
                        print(e)
                    sys.exit(1)
            elif target_is_through:
                ok, msg, errors, warnings = check_through_layer(args.target, target_path)
            elif target_is_dependent:
                r = build_dependent_layer(args.target, target_path, target_dep_paths)
                layer_ok = len(r["overlaid"]) == 0
                ok = layer_ok
                msg = f"{args.target}: {r['total_source']} files {'unchanged' if layer_ok else 'differ'}"
                errors = [f"~ {f}" for f in r["overlaid"]] if not layer_ok else []
                warnings = []
            else:
                ok, msg, errors, warnings = check_layer(args.target, target_path, LAYER_CHAIN)
            if ok:
                icon = "[WARN]" if warnings else "[OK]"
                print(f"{icon} {msg}")
                for w in warnings:
                    print(w)
                sys.exit(0)
            else:
                print(f"[ERR] {msg}")
                for e in errors:
                    print(e)
                for w in warnings:
                    print(w)
                sys.exit(1)
        else:
            ok = check_all()
            sys.exit(0 if ok else 1)
    else:
        if args.target:
            if target_is_packages:
                r = build_packages()
                print(f"[OK] packages: {r['total_source']} source files")
                for f in r["overlaid"]:
                    print(f"   + {f}")
                return
            elif target_is_through:
                r = build_through_layer(args.target, target_path)
            elif target_is_dependent:
                r = build_dependent_layer(args.target, target_path, target_dep_paths)
            else:
                r = build_layer(args.target, target_path, LAYER_CHAIN)
            print(f"[OK] {args.target}: {r['total_source']} source files")
            for f in r["overlaid"]:
                print(f"   + {f}")
            for f in r["stale"]:
                print(f"   ~ stale: {f}")
        else:
            build_all()


if __name__ == "__main__":
    main()
