name = "text-cli-api"
main = "src/index.js"
compatibility_date = "2026-05-01"
workers_dev = true

# D1 数据库
[[d1_databases]]
binding = "DB"
database_name = "text-cli-api-db"
database_id = "e9c0a2a7-e841-48db-97c4-c026efa1d6f9"

[vars]
ENDPOINT_BASE_URL = "https://text-cli-api.realearth.world"
ACCESS_TOKEN_REQUIRED = "false"
FORWARD_TIMEOUT = "30"
FORWARD_MAX_RETRIES = "1"
